print("Ingrese los datos de la division")
dividendo=int(input("Ingrese el numero del dividendo: "))
divisor =int(input("Ingrese el  numero divisor: "))
division = divmod(dividendo,divisor)
print(division)
